apiVersion: v1
kind: Service
metadata:
  name: stats-service
  namespace: demo-devops
  labels:
    app: stats-service
spec:
  type: NodePort
  selector:
    app: stats-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30081
