apiVersion: v1
kind: ConfigMap
metadata:
  name: stats-config
  namespace: demo-devops
data:
  # Configuration application
  PORT: "3002"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  ENABLE_METRICS: "true"
  # URL du service tasks (utilisé par le stats-service) - utiliser le port du Service (80)
  TASKS_SERVICE_URL: "http://tasks-service:80"
