
apiVersion: v1
kind: ConfigMap
metadata:
  name: tasks-config
  namespace: demo-devops
data:
  # Configuration application
  PORT: "3000"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  ENABLE_METRICS: "true"
  # Configuration base de données (non sensible)
  DB_HOST: "host.docker.internal"
  DB_PORT: "5432"
  DB_NAME: "taskdb"
  DB_USER: "taskuser"
