# ACME challenge and redirect to HTTPS (used when TLS/Let's Encrypt enabled)
server {
  listen 80;
  server_name _;

  # Let's Encrypt validation path
  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  # Redirect other traffic to HTTPS (if certs are present)
  location / {
    return 301 https://$host$request_uri;
  }
}
